### ISSUE TITLE
Include note subheadings in search terms

### ISSUE THREAD

**Issue by RyanT5** [penalosa/yformatics.com#9]
Based on my testing, search terms with a note subheading that does not appear as body text in note x does not return note x as a result. Please correct me if I am wrong or fix if I am right.

**Comment by penalosa** [comment]
Could you give me an example?

**Comment by RyanT5** [comment]
After some further testing the problem may actually be that the search results seem to only be able to display maximum 10 results and at 10 it doesn't scroll to the bottom of the list properly.

For example, try searching "Bayes' theorem".
